spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: admin
    password: xa36ta
  flyway:
    baseline-on-migrate: true


